records:
  A1:
    recordCount: 2
    fields:
      - name: record type 
        values: [A1]
        randomness: false 
      - name: id
        values: [0, 1000, 999]
        randomness: true 
      - name: login
        values: [user, admin]
        randomness: true 
  B2:
    recordCount: 5
    fields:
      - name: record type
        values: [B2]
        randomness: false 
      - name: login 
        values: [user, admin]
        randomness: true
      - name: currency 
        values: [Euro, Pln]
        randomness: true 
outputFilePath: /tmp/generated_file.csv
